--- 
- name: install system
  hosts: localhost
  pre_tasks:
    - name: update and upgrade the system
      become: true
      apt:
         update_cache: yes
         upgrade: no
         state: present
      ignore_errors: yes
        
- hosts: localhost
  name: starting git roles
  vars_prompt:
    - name: install_wifi
      prompt: Do you want to install rt8821ce wifi driver (yes/no)
      private: false
  roles:
    - { role: git, tags: git }
    - { role: terminals, tags: terminals }
    - { role: editor, tags: editor }
    - { role: languages, tags: languages }
    - { role: core, tags: core }
    - { role: addons, tags: addons }
    - { role: config, tags: config }
    - { role: game, tags: game }
    - { role: wayland, tags: wayland }
    - { role: docker, tags: docker }
    - { role: wifi, tags: wifi }
