--- 
- name: install system
  hosts: localhost
  pre_tasks:
    - name: update and upgrade the system
      become: true
      apt:
         update_cache: yes
         upgrade: yes
         state: present
      ignore_errors: yes
        
- hosts: localhost
  name: starting git roles
  roles:
    - git
  tags: git

- hosts: localhost
  name: starting terminal roles
  roles:
    - terminals
  tags: terminals
    
- hosts: localhost
  name: starting editor roles
  roles:
    - editor
  tags: editor

    
- hosts: localhost
  name: starting languages roles
  roles:
    - languages
  tags: languages
    
    
- hosts: localhost
  name: starting core roles
  roles:
    - core
  tags: core
    
- hosts: localhost
  name: starting addons roles
  roles:
    - addons
  tags: addons

- hosts: localhost
  name: starting dotfile roles
  roles:
    - config
  tags: config
    
- hosts: localhost
  name: start gaming roles
  roles:
    - game
  tags: game
    
- hosts: localhost
  name: start docker roles
  roles:
    - docker
  tags: docker
    
