---
- name: required libraries for brave
  become: yes
  apt:
    name: ["curl", "apt-transport-https"]

- name: Brave Browser archive-keyring.gpg download
  shell: |
     curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
     echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"| tee /etc/apt/sources.list.d/brave-browser-release.list
     apt update
     apt install brave-browser
      


- name: zettler installation
  get_url:
    url: https://github.com/Zettlr/Zettlr/releases/download/v2.2.6/Zettlr-2.2.6-amd64.deb
    dest: /home/drkknght/
  become: yes
  become_user: drkknght

- name: deb package
  become: yes
  apt:
    deb: /home/drkknght/Zettlr-2.2.6-amd64.deb
