---
- name: install stow
  apt:
    name: stow
    update_cache: no
  become: yes

- name: clone dotfiles
  git:
    repo: https://github.com/drkknigt/.dotfiles.git
    dest: $HOME/.dotfiles

  
- name: remove stuff
  shell: |
     rm -rf /home/drkknght/tmux /home/drkknght/polybar /home/drkknght/picom /home/drkknght/.bashrc /home/drkknght/.zshrc /home/drkknght/.tmux.conf /home/drkknght/.profile
  become: yes
  
- name: stow dotfiles
  become: yes
  shell: |
    cd ~/.dotfiles && stow */
  become_user: drkknght

- name: clone wallpapers
  git:
    repo: https://github.com/drkknigt/wall.git
    dest: $HOME/wall


- name: move wallpapers to pictures
  shell: |
    cp $HOME/wall/* $HOME/Pictures/ -r
  
- name: change permission
  shell: |
     chmod +x ~/bin -R
     chmod +x ~/.fehbg
