- name: make dir fonts
  file:
    path: $HOME/.local/share/fonts
    state: directory

- name: install fonts
  unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip
    dest: $HOME/.local/share/fonts
    remote_src: yes

