---
- name: install fzf from source
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: /home/drkknght/.fzf
    depth: 1

- name: build from source
  shell: |
    yes | $HOME/.fzf/install
    mv $HOME/.fzf/bin/fzf $HOME/.local/bin/

