---
- name: rm previous versions of Go
  file:
    path: /usr/local/go
    state: absent
  become: yes 

- name: download go source code
  unarchive:
    src: https://go.dev/dl/go1.20.5.linux-amd64.tar.gz
    dest: /usr/local/
    remote_src: yes
  become: yes
