---
- name: install misc software
  apt:
    name: ["ranger","tldr","htop","zathura","vlc","cmake","rofi","nitrogen","fd-find","lxappearance","arandr","bat","vnstat","xwallpaper","brightnessctl","tree","xautolock","kcolorchooser","conky","feh","virt-manager","lm-sensors","hddtemp","psensor","qbittorrent","telegram-desktop"]
    update_cache: yes
    
- name: install keys
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 41468D9A516AB58268042C6768CCF87596E97291
    
- name: install lazygit repo
  apt_repository:
     repo: deb https://ppa.launchpadcontent.net/lazygit-team/release/ubuntu focal main 
     state: present
     update_cache: True

- name: install lazygit
  apt:
    name: lazygit
    update_cache: True
     
- name: ripgrep installation
  get_url:
    url: https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
    dest: /home/drkknght/
  become: yes
  become_user: drkknght
  
- name: deb package
  become: yes
  apt:
    deb: /home/drkknght/ripgrep_13.0.0_amd64.deb
