---
- name: install node lts
  become: yes
  apt:
     name: ["nodejs","npm"]
     update_cache: yes
     
- name: install n
  become: yes
  community.general.npm:
      name: n
      global: yes

- name: install latest lts
  become: yes
  shell: |
     n lts
