---
- name: install python3
  become: yes
  apt:
    name: ["python3.9","python3-pip","python3.9-venv","make","build-essential","libssl-dev","zlib1g-dev","nlibbz2-dev","libreadline-dev","libsqlite3-dev","wget","curl","llvm","libncurses5-dev","nlibncursesw5","xz-utils","tk-dev","libffi-dev,"liblzma-dev","python-openssl","git"]
    update_cache: True

- name: install python libraries
  pip:
    name: ["black","flake8","mypy","autopep8","pylint","playsound","pytube","pyowm","pyftpdlib","pytest"]
  become: yes
  become_user: drkknght

- name: install poetry 
  shell: |
    curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
  become: yes
  become_user: drkknght

- name: install pyenv 
  shell: |
    curl https://pyenv.run | bash
    echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshrc
    echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshrc
    echo 'eval "$(pyenv init -)"' >> ~/.zshrc
  become: yes
  become_user: drkknght
  
  
