---
- name: install keys
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 3A160895CC2CE253085D08A552B24DF7D43B5377
    
- name: install ppa for alacritty
  become: True
  apt_repository:
    repo: deb https://ppa.launchpadcontent.net/aslatter/ppa/ubuntu focal main
    state: present
    

- name: install alacritty
  become: True
  apt:
     name: alacritty
     update_cache: yes
  

- name: make bin
  file:
    path: $HOME/.local/bin
    state: directory
  become: yes
  become_user: drkknght

 
- name: install kity
  shell: curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
  become: yes
  become_user: drkknght
  

- name: symbolic link to kity executable
  file:
     src: "$HOME/.local/kitty.app/bin/kitty" 
     dest: "$HOME/.local/bin"
     state: link
  become: yes
  become_user: drkknght
  
