---
- name: install keys
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 4AB0F789CBA31744CC7DA76A8CF63AD3F06FC659
    
- name: install vim and dependencies
  become: True
  apt_repository:
     repo: deb https://ppa.launchpadcontent.net/jonathonf/vim/ubuntu focal main
     state: present
     update_cache: True

- name: install vim and xclip
  become: True
  apt:
    name: ["vim-nox","vim-gtk3","xclip",'ninja-build', 'gettext', 'libtool' ,'libtool-bin', 'autoconf', 'automake', 'cmake', 'g++' ,'pkg-config' ,'unzip','curl', 'doxygen'
]
    update_cache: yes

- name: clone neovim
  git:
    repo: https://github.com/neovim/neovim
    dest: $HOME/neovim
  become: yes
  become_user: drkknght

- name: build neovim release from source
  shell: |
    cd $HOME/neovim && make CMAKE_BUILD_TYPE=Release CMAKE_INSTALL_PREFIX=$HOME/.local/ install
  become: yes
  become_user: drkknght


- name: install neovim
  get_url:
    url: https://github.com/neovim/neovim/releases/download/v0.7.0/nvim.appimage
    dest: $HOME/.local/bin/nvim_0.7
  become: yes
  become_user: drkknght
  
  
- name: change permission
  file:
    path: $HOME/.local/bin/nvim_0.7
    owner: drkknght
    group: drkknght
    mode: '0755'
  become: yes
  become_user: drkknght

- name: make undodir for nvim
  file:
    path: $HOME/textedit/nvim/undodir
    state: directory
  become: yes
  become_user: drkknght
  
- name: make undodir for vim
  file:
    path: $HOME/textedit/vim/undodir
    state: directory
  become: yes
  become_user: drkknght
