---
- name: install keys
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 4AB0F789CBA31744CC7DA76A8CF63AD3F06FC659
    
- name: install vim and dependencies
  become: True
  apt_repository:
     repo: deb https://ppa.launchpadcontent.net/jonathonf/vim/ubuntu focal main
     state: present
     update_cache: True

- name: install vim and xclip
  become: True
  apt:
    name: ["vim-nox","vim-gtk3","xclip"]
    update_cache: yes

- name: install neovim
  get_url:
    url: https://github.com/neovim/neovim/releases/download/v0.7.0/nvim.appimage
    dest: $HOME/.local/bin/nvim
  become: yes
  become_user: drkknght
  
  
- name: change permission
  shell: |
     chmod +x ~/.local/bin/nvim
  become: yes
  become_user: drkknght

- name: make undodir for nvim
  file:
    path: $HOME/textedit/nvim
    state: directory
  become: yes
  become_user: drkknght
  
- name: make undodir for vim
  file:
    path: $HOME/textedit/vim
    state: directory
  become: yes
  become_user: drkknght
