---
- name: Install ZSH
  apt: name=zsh
    
- name: Change shell to zsh
  shell: usermod --shell /bin/zsh drkknght

- name: Check that the somefile.conf exists
  stat:
    path: /home/drkknght/.oh-my-zsh
  register: oh_my_stats

- name: Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  when: oh_my_stats.stat.exists == False
  become_user: drkknght

- name: Install zsh-autosuggestions
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions"
  become: yes
  become_user: drkknght
