---
- name: clone hyprpicker
  git:
    repo: https://github.com/hyprwm/hyprpicker
    dest: $HOME/hyprpicker

- name: build wev
  become: true
  shell: |
    cd /home/{{ current_user }}/hyprpicker
    make all
    cp ./build/hyprpicker /home/{{ current_user }}/usr/bin/
