---
- name: clone sway-idle-audio
  git:
    repo: https://github.com/ErikReider/SwayAudioIdleInhibit
    dest: $HOME/SwayAudioIdleInhibit

- name: build wev
  become: true
  shell: |
    cd /home/drkknght/SwayAudioIdleInhibit
    meson build
    ninja -C build
    meson install -C build
