---
- name: install sway dependencies
  become: True
  apt:
    name: ['sway', 'wayland-protocols', 'waylandpp-dev', 'wayland-scanner++', 'waypipe', 'wayvnc']
    update_cache: True
  ignore_errors: yes

- name: install tools for sway
  become: True
  apt: 
    name: ['swayimg','swaybg','grim','grimshot','slurp','swayidle','swaylock','wlr-randr','mako-notifier','wl-clipboard','wmctrl','wdisplays','wofi']
  ignore_errors: yes
