---
- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "{{ git_email}}"

- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: drkknght
  
- name: name the master branch to main
  git_config:
    name: init.defaultBranch
    scope: global
    value: "{{ git_branch }}"

