---
- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"

- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: drkknght
  
- name: name the master branch to main
  git_config:
    name: init.defaultBranch
    scope: global
    value: "{{ git_branch }}"

- name: set core editor
  git_config:
    name: core.editor
    scope: global
    value: "nvim"

- name: set core pager
  git_config:
    name: core.pager
    scope: global
    value: "delta"
      
- name: set interactive options
  git_config:
    name: interactive.diffFilter
    scope: global
    value: "delta --color-only"

- name: set delta options
  git_config:
    name: delta.navigate
    scope: global
    value: "true"
      
      
- name: set delta options
  git_config:
    name: delta.light
    scope: global
    value: "true"
      
- name: set merge options
  git_config:
    name: merge.conflictstyle
    scope: global
    value: "diff3"
      
- name: set diff options
  git_config:
    name: diff.colorMoved
    scope: global
    value: "default"

- name: install ssh key
  get_url:
    url: https://raw.githubusercontent.com/drkknigt/.ansible_sync/main/key1
    dest: $HOME/test_ans/key1
    owner: "{{ current_user }}"
    group: "{{ current_user }}"
    mode: 0600
  tags: ssh_key

- name: ansible-vault
  command: ansible-vault decrypt $HOME/test_ans/key1
