---
- name: make .ssh dir
  file:
    path: $HOME/.ssh
    state: directory

- name: install vim and xclip
  become: True
  apt:
    name: ["ssh-askpass"]
    update_cache: yes
  ignore_errors: yes
      
- name: install ssh key
  get_url:
    url: https://raw.githubusercontent.com/drkknigt/.ansible_sync/main/clone
    dest: $HOME/.ssh/id_ed25519
    owner: "{{ current_user }}"
    group: "{{ current_user }}"
    mode: 0600

- name: ansible-vault
  command: ansible-vault decrypt $HOME/.ssh/id_ed25519

- name: add password for ssh
  shell: ssh-add $HOME/.ssh/id_ed25519

- name: test ssh
  shell: ssh -T git@github.com
  ignore_errors: true
