---
- name: make .ssh dir
  file:
    path: $HOME/.ssh
    state: directory
  tags: ssh

- name: Install ssh key private
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags: ssh

- name: Install ssh key public
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
  tags: ssh

- name: add ssh key
  shell: |
    { sleep .1; echo "{{ ssh_pass }}"; } | script -q /dev/null -c 'ssh-add "{{ dest_key }}"'
  ignore_errors: True
  tags: [ssh_test,ssh]

- name: connect to github
  shell: |
    ssh -T -o StrictHostKeyChecking=accept-new git@github.com
  ignore_errors: True
  tags: [ssh_test,ssh]


- name: install ssh askpkass
  become: True
  apt:
    name: ["ssh-askpass"]
    update_cache: yes
  ignore_errors: yes
  tags: ssh
