---
- name: clone dotfiles
  command: git clone git@github.com:drkknigt/.dotfiles.git $HOME/.dotfiles

- name: clone ansible
  command: git clone git@github.com:drkknigt/.ansible_sync $HOME/.ansible_sync
