---
- name: required libraries for brave
  become: yes
  apt:
    name: ["curl", "apt-transport-https"]

- name: Brave Browser archive-keyring.gpg download
  become: yes
  shell: |
     curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
     echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"| tee /etc/apt/sources.list.d/brave-browser-release.list

- name: install brave
  become: yes
  apt:
    name: brave-browser
    update_cache: yes
  ignore_errors: yes
