---
- name: install keys
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 41468D9A516AB58268042C6768CCF87596E97291
  become: yes
  ignore_errors: yes
    
- name: install lazygit repo
  apt_repository:
     repo: deb https://ppa.launchpadcontent.net/lazygit-team/release/ubuntu focal main 
     state: present
     update_cache: True
  become: yes
  ignore_errors: yes

- name: install lazygit
  apt:
    name: lazygit
    update_cache: True
  become: yes
  ignore_errors: yes
