---
- name: install utilities software
  apt:
    name: ["ranger","tldr","htop","vlc","cmake","rofi","nitrogen","lxappearance","arandr","bat","vnstat","xwallpaper","brightnessctl","tree","xautolock","kcolorchooser","conky","feh","virt-manager","lm-sensors","psensor","qbittorrent","qalc","smartmontools","gsmartcontrol","gimp","ffmpeg","mediainfo","testdisk","cpufrequtils","cpupower-gui","xcvt","acpitool","checkinstall","power-profiles-daemon","powertop","cheese","pavucontrol","sddm","shellcheck"]
    update_cache: yes
  become: yes
  ignore_errors: yes
  tags: os-utilities


- name: install social networking software
  apt:
    name: ["telegram-desktop"]
    update_cache: yes
  become: yes
  ignore_errors: yes
  tags: social
      
- name: install network tools
  apt:
    name: ["openssh-server","proxychains","tor","wireshark","nmap","whois"]
    update_cache: yes
  become: yes
  ignore_errors: yes
  tags: net-tools
      
- name: install network tools
  apt:
    name: ["openssh-server","proxychains","tor","wireshark"]
    update_cache: yes
  become: yes
  ignore_errors: yes
  tags: net-tools
      
- name: install pdf tools
  apt:
    name: ["pandoc","texlive-latex-base","texlive-fonts-recommended","texlive-extra-utils","texlive-latex-extra","texlive-xetex"]
    update_cache: yes
  become: yes
  ignore_errors: yes
  tags: pdf-tools
