---
- name: install utilities software
  apt:
    name: ["tldr","htop","mpv","cmake","rofi","nitrogen","lxappearance","arandr","bat","vnstat","xwallpaper","brightnessctl","tree","xautolock","kcolorchooser","feh","virt-manager","lm-sensors","psensor","qbittorrent","qalc","smartmontools","gsmartcontrol","gimp","ffmpeg","mediainfo","testdisk","cpupower-gui","xcvt","acpitool","checkinstall","tlp","tlp-rdw","powertop","cheese","pavucontrol","sddm","shellcheck","i3blocks","xdotool","udiskie"]
    update_cache: yes
  become: yes
  ignore_errors: yes
  tags: os-utilities


- name: install cpupower 
  apt:
    name: [ "cpufrequtils","cpufreqd"]
    update_cache: yes
  become: yes
  ignore_errors: yes
  tags: os-utilities-power


- name: install social networking software
  apt:
    name: ["telegram-desktop"]
    update_cache: yes
  become: yes
  ignore_errors: yes
  tags: social
      
- name: install network tools
  apt:
    name: ["openssh-server","proxychains","tor","wireshark","nmap","whois"]
    update_cache: yes
  become: yes
  ignore_errors: yes
  tags: net-tools
      
      
- name: install pdf tools
  apt:
    name: ["pandoc","texlive-latex-base","texlive-fonts-recommended","texlive-extra-utils","texlive-latex-extra","texlive-xetex"]
    update_cache: yes
  become: yes
  ignore_errors: yes
  tags: pdf-tools
    
- name: make user bin directory
  file:
    path: $HOME/usr/bin
    state: directory
  tags: delta

- name: extract tar.gz 
  unarchive:
    src: https://github.com/dandavison/delta/releases/download/0.15.0/delta-0.15.0-x86_64-unknown-linux-gnu.tar.gz
    dest: /tmp
    remote_src: yes
  tags: delta

- name: copy delta from tmp
  copy:
    src: /tmp/delta-0.15.0-x86_64-unknown-linux-gnu/delta
    dest: $HOME/usr/bin
    owner: "{{ current_user }}"
    group: "{{ current_user }}"
    mode: '0711'
  tags: delta
