---
- name: install keys
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: F2C37BD8BDF01321549242C9AEC82AC78B65E182
  become: yes
  ignore_errors: yes
  tags: zathura
    
- name: install zathura repo
  apt_repository:
     repo: deb https://ppa.launchpadcontent.net/spvkgn/zathura-mupdf/ubuntu focal main
     state: present
     update_cache: True
  become: yes
  ignore_errors: yes
  tags: zathura

- name: install zathura
  apt:
    name: ["zathura","zathura-djvu","zathura-pdf-mupdf"]
    update_cache: true
  become: yes
  ignore_errors: yes
  tags: zathura
