---
- name: add repos for wezterm to apt
  shell: |
     curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /usr/share/keyrings/wezterm-fury.gpg
     echo 'deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *' | sudo tee /etc/apt/sources.list.d/wezterm.list
  become: yes
  tags: wezterm_repo

- name: install wezterm
  become: yes
  apt: 
    name: wezterm
    update_cache: true
  tags: install_wezterm

    
    
  
