---
- name: install python
  import_tasks: python.yml
  tags: python
  

- name: install clangd
  import_tasks: clangd.yml
  tags: clangd
    
- name: install lua
  import_tasks: lua.yml
  tags: lua
  

- name: install rust
  import_tasks: rust.yml
  tags: rust
    
- name: install go
  import_tasks: go.yml
  tags: go
    
- name: install node
  import_tasks: node.yml
  tags: node
